In [2]:
# Creating Numpy arrays
import numpy as np

# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)



In [28]:
my_array1

array([1, 2, 3, 4])

In [11]:
arr1 = np.arange(4, 100, 5)
arr1.ndim

1

In [9]:
obj = [[2, 4], [1, 8]]
arr2 = np.array(obj)

In [26]:
obj3dm = [[[2, 1], [3, 6]], [[5, 8], [6, 9]], [[0, 4], [8, 6]]]
arr3 = np.array(obj3dm)
print(arr3.ndim)
print(arr3.shape)
print(arr3)

3
(3, 2, 2)
[[[2 1]
  [3 6]]

 [[5 8]
  [6 9]]

 [[0 4]
  [8 6]]]


In [50]:
print(arr3 * 5)

[[[10  5]
  [15 30]]

 [[25 40]
  [30 45]]

 [[ 0 20]
  [40 30]]]


In [27]:
arr3[1, 0, 1]

8

In [30]:
arr2.shape

(2, 2)

In [ ]:
#Print out array

my_array

In [39]:
# Make another list
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2.T

array([[ 1, 11],
       [ 2, 22],
       [ 3, 33],
       [ 4, 44]])

In [31]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [32]:
#Find out the data tyoe of the array
my_array2.dtype

dtype('int64')

In [37]:
objmixed = [['1', 'blue', '6', '8'], ['4', 'redredredred', '3', '10']]
arr4 = np.array(objmixed)
arr4.dtype

dtype('<U12')

In [36]:
items = ['Man', 'Woman']
arr5 = np.array(items)
arr5.dtype

dtype('<U5')

In [42]:
#Making special case arrays

#Zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
#Ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
# An empty array

print(np.empty(10))
print(np.empty((3,4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[9.9e-324 4.9e-324 1.5e-323 3.0e-323]
 [2.5e-323 4.0e-323 3.0e-323 4.4e-323]
 [0.0e+000 2.0e-323 4.0e-323 3.0e-323]]


In [49]:
#Identity array
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# Using a range

np.arange(5)