In [1]:
import numpy as np

In [ ]:
5/2

In [2]:
# Create array

arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1


array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [3]:
#Multiplying Arrays
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [4]:
#Subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
#Arithmetic operations with scalars on array
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.125     , 0.11111111, 0.1       ]])

In [6]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])

In [12]:
obj1 = [[1,2,3], [2,3,4]]
obj2 = [[1,2], [2,3], [3, 4]]
arr2 = np.array(obj1)
arr3 = np.array(obj2)
print(arr2.ndim)
print(arr3.ndim)
print(arr2.shape)
print(arr3.shape)

2
2
(2, 3)
(3, 2)


In [35]:
"""
same dimentional array but different shape cannot be multiplied unless reshaped to a corresponding shape size of both arrays being multiplied together.
"""
#arr2 * arr3

'\nsame dimentional array but different shape cannot be multiplied unless reshaped to a corresponding shape size of both arrays being multiplied together.\n'

In [16]:
arr4 = arr3.reshape((1, 2, 3))

In [31]:
arr5 = np.concatenate((arr4, np.array([[[2,3,4],[4,5,3]]])), axis=1)

In [34]:
arr5

array([[[1, 2, 2],
        [3, 3, 4],
        [2, 3, 4],
        [4, 5, 3]]])

In [22]:
arr6 = np.array([[3,4], [4,6]])
arr7 = np.array([[4,9], [0,8]])

In [23]:
print(arr6)
print(arr7)

[[3 4]
 [4 6]]
[[4 9]
 [0 8]]


In [37]:
arr8 = np.concatenate((arr6, arr7), axis=1)

In [40]:
arr8

array([[3, 4, 4, 9],
       [4, 6, 0, 8]])

In [41]:
arr8[0:1,0:3]

array([[3, 4, 4]])

In [42]:
arr8[:, 0:3]

array([[3, 4, 4],
       [4, 6, 0]])